### ISSUE TITLE
Previsão para recebedores secundarios/comissionados

### ISSUE THREAD

**Issue by ulisses-almeida-mowa** [Irio/mymoip#18]
Tem previsão para adicionar essa funcionalidade nessa sua gem? http://labs.moip.com.br/referencia/secundarios/

Fui olhar a lib de ruby "oficial", mas ela está há um ano sem atualização.

**Comment by Irio** [comment]
Não implementei porque não vi necessidade até então nos sistemas que a mymoip foi usada.

Referente à implementação dessa feature, não conheço nenhum caminho para conseguir esse "LoginMoIP", então deveria ser setado diretamente por você no código (imagino deve deve ser o nickname ou o e-mail usado no cadastro, precisaria fazer testes para verificar).

**Comment by ulisses-almeida-mowa** [comment]
Obrigado pela resposta. Vou fazer um fork desse projeto com minha conta pessoal e vou tentar adicionar essa feature. Depois mando um pull se ficar bom!

**Comment by Irio** [comment]
Faz o pull request mesmo se não ficar, ai conversamos para deixá-lo bom :+1:

**Comment by Irio** [comment]
Implementado no #19, já disponível no master branch.
