### ISSUE TITLE
Readme with wrong parameter for new commission

### ISSUE THREAD

**Issue by ulissesalmeida** [Irio/mymoip#20]
Lembra que vc me pediu para trocar o commissioned para receiver_login, eu já mudei antes de vc realizar o merge. O certo seria:

``` ruby
commissions = [MyMoip::Commission.new(
  reason: 'System maintenance',
  receiver_login: 'commissioned_moip_login',
  fixed_value: 15.0
)]
```

**Comment by Irio** [comment]
Seria isso do c184b4a, @ulissesalmeida?

**Comment by ulisses-almeida-mowa** [comment]
Sim

**Comment by Irio** [comment]
Beleza, então já foi corrigido.

Pretendo fazer mais alguns testes e lançar uma nova versão com essa tua feature até amanhã.

**Comment by ulissesalmeida** [comment]
Lega! Fico no aguardo!
