### ISSUE TITLE
Baixando versão antiga via gemfile

### ISSUE THREAD

**Issue by iurichiba** [Irio/mymoip#21]
Bom dia,

Estamos utilizando a gem mymoip no nosso projeto, mas encontramos um estranho problema: ao colocarmos esta gem no gemfile e instalá-la, recuperamos uma versão antiga (mas nomeada 0.4.0), sem suporte para comissionamento e comandos diferentes para o sandbox. Estranhamos que alguns comandos não estavam sendo reconhecidos e nossa solução foi manual, substituindo os arquivos. Você está ciente de algum problema com a sincronia da gema?

Muito obrigado pela ajuda.

Atenciosamente,
Iuri Chiba.

**Comment by Irio** [comment]
Bom dia @iurichiba!

Olha, não tive nenhuma notícia desse tipo. Você poderia postar o `Gemfile.lock` do teu projeto?

**Comment by iurichiba** [comment]
Bom dia, @Irio!

Desculpe-me pela demora, mas acredito que você esteja querendo saber qual versão do mymoip está instalada, de acordo com o arquivo, e eu já havia checado na esperança que fosse esse o problema mas está marcado como 0.4.0, mesmo.

Mas notei que você editou o projeto há 4 dias atualizando o Gemfile, então testarei novamente assim que possível e te aviso se ocorreu algum problema novamente.

Obrigado pela ajuda!

**Comment by Irio** [comment]
Atualizei mas mesmo assim a versão `0.4.1`. Tenta dar um `bundle update mymoip` para ver se corrige, por favor.

**Comment by Irio** [comment]
Fechando a issue.

@iurichiba, se voltar a acontecer, por favor nos avise.
