### ISSUE TITLE
Wrong validation on credit card

### ISSUE THREAD

**Issue by zangrandi** [Irio/mymoip#30]
The regex that is validating the expiration date of credit card is wrong, it's not accepting the month "11".

```
/\A(?:(?:0[1-9])|(?:1[02]))\/\d{2}\Z/
```

I think this would resolve the problem:

```
/\A(?:(?:0[1-9])|(?:1[0-2]))\/\d{2}\Z/
```

**Comment by Irio** [comment]
It's correct. Can you submit a patch fixing it?
