### ISSUE TITLE
Credit card validations

### ISSUE THREAD

**Issue by hugomaiavieira** [Irio/mymoip#39]
@Irio some credit card attributes (:owner_name, :owner_cpf and :card_number) doesn't have any validation. There are some reason for it? Can I add a validation for the presence of these attributes?

**Comment by hugomaiavieira** [comment]
On [Moip javascript](https://desenvolvedor.moip.com.br/sandbox/transparente/MoipWidget-v2.js) they validate the presence of owner_name and do this validation for owner_cpf:

``` javascript
cpfEhValido = function(cpf) {

  cpf = String(cpf).replace(/\D/g, "");

  if (cpf.length != 11)
    return false;

  return true;
}
```

And this to the card_number:

``` javascript
  validarNumeroDoCartao = function(cartao, instituicao) {

    var numero = cartao.Numero;

    if (naoInformou(numero)) {
      adicionarErro(905, "Informe o número do cartão");

    } else {
      var qtdCaracteres = String(numero).length;

      if (instituicao == "Visa" && qtdCaracteres != 16) {
        adicionarErro(905, "Número de cartão inválido");
      }
      else if (instituicao == "Mastercard" && qtdCaracteres != 16) {
        adicionarErro(905, "Número de cartão inválido");
      }
      else if (instituicao == "AmericanExpress" && (qtdCaracteres < 15 || qtdCaracteres > 16)) {
        adicionarErro(905, "Número de cartão inválido");
      }
      else if (instituicao == "Diners" && qtdCaracteres != 14) {
        adicionarErro(905, "Número de cartão inválido");
      }
      else if (instituicao == "Hipercard" && (qtdCaracteres < 13 || qtdCaracteres > 19 || qtdCaracteres == 17 ||qtdCaracteres == 18)) {
        adicionarErro(905, "Número de cartão inválido");
      }
    }
  };
```

Can I add this validations (with a better code)?

**Comment by Irio** [comment]
That's because the API itself don't requires those attributes to return a [successful response](https://gist.github.com/Irio/4032350).

This bug is already [reported](https://labs.moip.com.br/forum/showthread.php?3462-Campos-requeridos-em-transa%E7%F5es-da-API-do-Checkout-Transparente) and no modification took place. Since MyMoip is just an interface with Moip's API, don't see reason to add an extra validation before the server.

**Comment by hugomaiavieira** [comment]
@Irio the problem is that this will generate an invalid moip transaction. It return ok at first, but moip will not complete the transaction. We don't want the user to not fill the creditcard number, for instance, because it will generate a invalid transaction. If we don't add the validations on the gem, I will have to open the CreditCard class to inject the validations =/

**Comment by Irio** [comment]
A good way to make explicit this bug from Moip while allowing to fix it without monkey patching or "fixing" the external API is add a flag in `MyMoip::CreditCard`.

``` ruby
# Initialization
MyMoip::CreditCard.new(logo: 'visa', perform_extra_validation: true)

# lib/mymoip/credit_card.rb
module MyMoip
  class CreditCard
    attr_accessor :perform_extra_validation

    validates_presence_of :card_number, :expiration_date, :owner_name,
                          :owner_phone, :owner_rg,
                          if: ->(resource) { resource.perform_extra_validation }
  end
end
```

What do you think about this?

**Comment by hugomaiavieira** [comment]
@Irio  :+1: 
I liked your solution and already did a pull request.
