### ISSUE TITLE
CreditCard Payment with one or more installments

### ISSUE THREAD

**Issue by JoseAurelianoJR** [Irio/mymoip#45]
I'm receiving this error from my request:

<pre>
  <code>
[2014-05-26T00:41:48.322588 #8360] DEBUG -- : MyMoip::TransparentRequest of #Ingresso - Teste to https://desenvolvedor.moip.com.br/sandbox/ws/alpha/EnviarInstrucao/Unica had response #<HTTParty::Response:0x35f8a68 parsed_response={"EnviarInstrucaoUnicaResponse"=>{"Resposta"=>{"ID"=>"201405252203414010000005107375", "Status"=>"Falha", "Erro"=>{"__content__"=>"O Valor Máximo de Parcelas não foi corretamente especificado (é obrigatório e deve ser maior do que zero)", "Codigo"=>"123"}}}}, @response=#<Net::HTTPOK 200 OK readbody=true>, @headers={"date"=>["Mon, 26 May 2014 01:03:40 GMT"], "server"=>["Apache"], "content-length"=>["331"], "vary"=>["Accept-Encoding"], "connection"=>["close"], "content-type"=>["text/xml;charset=UTF-8"]}>
</code>
</pre>

in my controller have this code:

<pre>
<code>
installments = [
      { min: 1, max:  1, forward_taxes: false },
      { min: 2, max: 12, forward_taxes: true,  fee: 1.99 } # 1.99 fee = 1.99% per month
    ]
</code>

    instruction = MyMoip::Instruction.new(
      id:             order.id,
      payment_reason: "Ingresso - #{@event.name}",
      values:         [order.price.to_f],
      payer:          payer,
      installments:   installments
    )

    transparent_request = MyMoip::TransparentRequest.new("Ingresso - #{@event.name}")
    transparent_request.api_call(instruction)
    
    
    credit_card_payment = MyMoip::CreditCardPayment.new(credit_card, installments: order.credit_card_information["purchase_installments"].to_i)
    payment_request     = MyMoip::PaymentRequest.new("Ingresso - #{@event.name}")
    payment_request.api_call(credit_card_payment, token: transparent_request.token)
</pre>

in my webrick console appears:

<pre>
<code>
MyMoip::TransparentRequest of #Ingresso - Teste with {:body=>"<EnviarInstrucao><InstrucaoUnica TipoValidacao=\"Transparente\"><Razao>Ingresso - Teste</Razao><Valores><Valor moeda=\"BRL\">220.00</Valor></Valores><IdProprio>6e1508ab89edd4c359ba88f8a5dfbfe142bae749</IdProprio><Parcelamentos><Parcelamento><MinimoParcelas>1</MinimoParcelas><MaximoParcelas>1</MaximoParcelas><Juros/></Parcelamento><Parcelamento><MinimoParcelas>2</MinimoParcelas><MaximoParcelas>12</MaximoParcelas><Repassar>true</Repassar><Juros>1.99</Juros></Parcelamento></Parcelamentos><Pagador><Nome>Jose Aureliano</Nome><Email>junior@bluevox.com.br</Email><IdPagador>ab1c4733798aa17f64ca7a1835eb2581e820d88f</IdPagador><EnderecoCobranca><Logradouro>dfgdfgdfgdfg</Logradouro><Numero>345</Numero><Complemento>dfgdfgdfg</Complemento><Bairro>s</Bairro><Cidade>Água Branca</Cidade><Estado>AL</Estado><Pais>BRA</Pais><CEP>34534-544</CEP><TelefoneFixo>(45)3453-4545</TelefoneFixo></EnderecoCobranca></Pagador></InstrucaoUnica></EnviarInstrucao>", :http_method=>:post, :requires_auth=>true, :path=>"/ws/alpha/EnviarInstrucao/Unica"}
</code>
</pre>

suggestions ?

**Comment by diegoqlima** [comment]
The error occurs because you're passing equal parameters at min/max installments.
The fix is:

```
installments = [
      { min: 2, max: 12, forward_taxes: true,  fee: 1.99 } # 1.99 fee = 1.99% per month
    ]
```
