### ISSUE TITLE
Parcelamento

### ISSUE THREAD

**Issue by vbrazo** [Irio/mymoip#7]
Como faço para possibilitar que o usuário parcele a compra em 3x ?

**Comment by Irio** [comment]
Ao instanciar o `CreditCardPayment`, passe o segundo parâmetro com o número de parcelas que tu quer.

```
MyMoip::CreditCardPayment.new(credit_card_object, 1)
```

**Comment by Irio** [comment]
Agora passa a ser melhor usar `MyMoip::CreditCardPayment.new(credit_card, installments: 1)`, como aconselhado no README.

**Comment by vbrazo** [comment]
Já alterei e ganhei esse erro de brinde hehe

2012-10-18T15:27:32+00:00 app[web.1]: NoMethodError (undefined method `[]'
for nil:NilClass):
2012-10-18T15:27:32+00:00 app[web.1]:
app/controllers/billing_controller.rb:75:in`success'

sendo que a minha linha 75 é

payment_request.api_call(credit_card_payment, token:
transparent_request.token)

2012/10/18 Irio Irineu Musskopf Junior notifications@github.com

> Agora passa a ser melhor usar MyMoip::CreditCardPayment.new(credit_card,
> installments: 1), como aconselhado no README.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Irio/mymoip/issues/7#issuecomment-9566189.

## 

_Vitor Oliveira_

**Comment by Irio** [comment]
Pode postar todo o log do erro?

**Comment by Irio** [comment]
O stack do erro que aconteceu para ti.

**Comment by Irio** [comment]
Me parece tudo certo. Se tu quiser resolver esse problema, abre uma outra issue com esse log e a action do controller que gera esse erro.
