### ISSUE TITLE
Problem with your custom .rvmrc

### ISSUE THREAD

**Issue by ghost** [Irio/mymoip#8]
Hey, please remove the .rvmrc configuration from your projects. It's creating a isolated environment on RVM and your gem is not visible from the default environment.

I think it should fix if you just remove the .rvmrc.

**Comment by Irio** [comment]
Could you try this version?

```
gem 'mymoip', git: 'git@github.com:Irio/mymoip.git', branch: 'requests_folder'
```

**Comment by Irio** [comment]
@klebershimabuku Pode fazer também um teste?

**Comment by klebershimabuku** [comment]
@Irio Testei aqui e aparentemente está funcionando apontando para este branch `requests_folder`. No entanto ao rodar `bundle`, recebi a seguinte reclamação:

```
mymoip at /home/developer5/.rvm/gems/ruby-1.9.2-p290@project/bundler/gems/mymoip-688a469d12a5 did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
[".rvmrc", "lib/mymoip/payment_request.rb", "lib/mymoip/transparent_request.rb"] are not files
```

**Comment by Irio** [comment]
@klebershimabuku Feito. Pode testar novamente?

**Comment by klebershimabuku** [comment]
@Irio Perfeito! :+1: 

Rodei `bundle update mymoip`

**Comment by Irio** [comment]
Now you can use `0.2.3` with this branch's code.

**Comment by klebershimabuku** [comment]
Thanks!

**Comment by ghost** [comment]
Everything is alright!! Thanks Irio
